"""Tier 5: the scoreboard against DEVSIM.

phases/PHASE-8.md. Tiers 1 to 4 ask whether ddsim is right. This one asks
whether it is better than DEVSIM, and it only reads numbers that were measured:
the CSVs in `data/scoreboard/`, generated by hand by `tools/scoreboard.py` and
`devsim_gen/scoreboard.py`, the same way the golden data is.

The capability matrix is the part that runs today. Every "yes" in it has to
point at something that exists: a test for ddsim, and for DEVSIM either a name
in the snapshot of its API or a function in the generators that scripts it. A
row whose evidence goes missing fails here, which is what stops a capability
quietly turning into a sentence in a README.
"""

from __future__ import annotations

import csv
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
"""The repository root. Evidence paths are relative to it."""

SCOREBOARD = ROOT / "data" / "scoreboard"
"""Where both generators write, and where this reads."""

CAPABILITY_COLUMNS = (
    "capability",
    "ddsim",
    "ddsim_evidence",
    "devsim",
    "devsim_evidence",
    "note",
)
"""The header of capabilities.csv, in order."""

DDSIM_VALUES = ("yes", "no")
"""ddsim either has a capability, with a test, or does not."""

DEVSIM_VALUES = ("yes", "scripted", "no")
"""yes: DEVSIM ships it. scripted: DEVSIM can do it once you write the
equations, and the evidence is where this repo wrote them or the API that
takes them. no: neither."""

SEPARATOR = " + "
"""Between two pieces of evidence in one cell."""


def _capabilities() -> list[dict[str, str]]:
    with (SCOREBOARD / "capabilities.csv").open(newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        assert tuple(reader.fieldnames or ()) == CAPABILITY_COLUMNS
        return list(reader)


def _devsim_api() -> set[str]:
    lines = (SCOREBOARD / "devsim_api.txt").read_text(encoding="utf-8").splitlines()
    return {line.strip() for line in lines if line.strip() and not line.startswith("#")}


def _function_exists(token: str) -> bool:
    """A `path::name` token names a function defined in a file of this repo."""
    path, _, name = token.partition("::")
    source = ROOT / path
    if not name or not source.is_file():
        return False
    return f"def {name}(" in source.read_text(encoding="utf-8")


def _evidence(cell: str) -> list[str]:
    return [token.strip() for token in cell.split(SEPARATOR) if token.strip()]


def test_the_capability_matrix_has_its_columns_and_values() -> None:
    rows = _capabilities()
    assert rows, "capabilities.csv has no rows"
    names = [row["capability"] for row in rows]
    assert len(names) == len(set(names)), "a capability is listed twice"
    for row in rows:
        assert row["ddsim"] in DDSIM_VALUES, row
        assert row["devsim"] in DEVSIM_VALUES, row


def test_every_ddsim_yes_cites_a_test_that_exists() -> None:
    missing = []
    for row in _capabilities():
        tokens = _evidence(row["ddsim_evidence"])
        if row["ddsim"] == "yes":
            if not tokens:
                missing.append(f"{row['capability']}: no evidence")
            for token in tokens:
                if not token.startswith("tests/") or not _function_exists(token):
                    missing.append(f"{row['capability']}: {token}")
        elif tokens:
            missing.append(f"{row['capability']}: evidence on a no")
    assert not missing, missing


def test_every_devsim_claim_cites_its_api_or_our_script() -> None:
    api = _devsim_api()
    missing = []
    for row in _capabilities():
        tokens = _evidence(row["devsim_evidence"])
        if row["devsim"] in ("yes", "scripted"):
            if not tokens:
                missing.append(f"{row['capability']}: no evidence")
            for token in tokens:
                found = _function_exists(token) if "::" in token else token in api
                if not found:
                    missing.append(f"{row['capability']}: {token}")
        elif tokens:
            missing.append(f"{row['capability']}: evidence on a no")
    assert not missing, missing


def test_the_devsim_api_snapshot_says_where_it_came_from() -> None:
    text = (SCOREBOARD / "devsim_api.txt").read_text(encoding="utf-8")
    header = [line for line in text.splitlines() if line.startswith("#")]
    assert any(line.startswith("# devsim ") for line in header), header
    assert any(line.startswith("# written ") for line in header), header


@pytest.mark.parametrize(
    "token",
    ["tests/nowhere.py::test_x", "tests/regression/test_scoreboard.py::no_such"],
)
def test_a_function_that_does_not_exist_is_not_evidence(token: str) -> None:
    assert not _function_exists(token)
