"""Tier 4: ddsim against DEVSIM golden data.

docs/04-validation.md opens by saying the project's credibility rests on this
tier, and until now it had never run: `data/golden/` held a `.gitkeep` and
nothing else. These tests compare ddsim's diode I-V against curves solved by
DEVSIM 2.11 with every model parameter matched, generated by
`devsim_gen/generate_diodes.py`.

What this tier can and cannot say:

- It is a comparison against an independent implementation of the same
  equations, not against measurement. Two codes agreeing means neither has an
  isolated blunder. It does not mean the model is right.
- Both codes run Boltzmann statistics, constant mobility and SRH only, because
  that is what ddsim has. Device 3 is labelled a degeneracy test in the doc,
  and with Boltzmann on both sides it is not one yet.
- Devices 4 to 9 in the benchmark table are the MOS capacitor and the MOSFETs.
  ddsim cannot solve them yet, so there is no golden data for them and no test
  here. The gap is deliberate and is recorded in PROGRESS.md rather than
  papered over with a skip that reads like a pass.

The tolerance policy is the interesting part. Each benchmark carries the
tolerance from the doc, but at low bias the terminal current is a cancellation
between drift and diffusion terms twelve decades larger, and no amount of
solver tolerance recovers digits that floating point has already thrown away.
The golden datum measures its own uncertainty: anode and cathode currents must
sum to zero in steady state, so whatever fails to cancel is the noise on that
point. The test demands the doc's tolerance or three times that noise,
whichever is looser, and never demands that ddsim match a number more closely
than that number agrees with itself.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from ddsim.core import constants as C
from ddsim.device.pn_diode import pn_diode
from ddsim.extract.iv import IVCurve, iv_sweep
from tests.regression.devsim_gen import parameters as P

GOLDEN_DIR = Path(__file__).resolve().parents[2] / "data" / "golden"
"""Where the generator writes, and where this reads."""

NOISE_FACTOR = 3.0
"""How much of the golden point's own current imbalance to allow [1].

Three, because the imbalance is an estimate of a rounding error rather than a
bound on one, and because a factor that admits every measured disagreement
today still leaves the tightest device sitting at a sixth of its budget.
"""


# ------------------------------------------------------------------ the mirror


@pytest.mark.parametrize(
    ("name", "mirror", "actual"),
    [
        ("q", P.Q, C.q),
        ("k_B", P.K_B, C.k_B),
        ("eps_0", P.EPS_0, C.eps_0),
        ("T", P.T, C.T_ROOM),
        ("eps_r_Si", P.EPS_R_SI, C.EPS_R_SI),
        ("n_i", P.N_I, C.N_I_300),
        ("mu_n", P.MU_N, C.MU_N_300),
        ("mu_p", P.MU_P, C.MU_P_300),
        ("tau_n_max", P.TAU_N_MAX, C.TAU_N_MAX),
        ("tau_p_max", P.TAU_P_MAX, C.TAU_P_MAX),
        ("tau_n_min", P.TAU_N_MIN, C.TAU_N_MIN),
        ("tau_p_min", P.TAU_P_MIN, C.TAU_P_MIN),
        ("N_ref_SRH", P.N_REF_SRH, C.N_REF_SRH),
        ("gamma_SRH", P.GAMMA_SRH, C.GAMMA_SRH),
        ("V_T", P.V_T, C.V_T()),
    ],
)
def test_generator_constants_mirror_ddsim(
    name: str, mirror: float, actual: float
) -> None:
    """Every constant the generator handed DEVSIM is still ddsim's value.

    The generator runs under a separate interpreter that cannot import ddsim,
    so its constants are literal copies. This is the test that stops the copies
    rotting: change a constant in ddsim and the golden data is stale, which is
    a failure here rather than a two percent drift nobody notices.
    """
    assert mirror == actual, (
        f"{name} is {mirror} in the generator and {actual} in ddsim. The "
        "golden data was solved with the generator's value, so it is stale. "
        "Regenerate it, do not edit the mirror."
    )


def test_generator_lifetime_matches_ddsim() -> None:
    """The Scharfetter lifetime helper agrees with ddsim's, not just its inputs.

    The constants test above pins tau_max and N_ref. This pins the shape of the
    curve they parameterise, which is the thing DEVSIM was actually handed as
    an expression string.
    """
    from ddsim.physics.recombination import scharfetter_lifetime

    for doping in (0.0, 1e14, 5e16, 1e18, 1e20):
        expected = float(
            scharfetter_lifetime(doping, tau_max=C.TAU_N_MAX, tau_min=C.TAU_N_MIN)
        )
        mirror = P.scharfetter_lifetime(doping, P.TAU_N_MAX, P.TAU_N_MIN)
        assert mirror == pytest.approx(expected, rel=1e-15)


# ------------------------------------------------------------- the golden data


def golden_path(benchmark: P.DiodeBenchmark) -> Path:
    """Where this benchmark's golden curve lives."""
    return GOLDEN_DIR / f"{benchmark.name}.csv"


@pytest.mark.parametrize("benchmark", P.BENCHMARKS, ids=lambda b: b.name)
def test_golden_data_exists(benchmark: P.DiodeBenchmark) -> None:
    """Tier 4 has data. An empty data/golden means this tier is not running."""
    assert golden_path(benchmark).is_file(), (
        f"no golden curve for {benchmark.name}. Generate it with "
        "tests/regression/devsim_gen/generate_diodes.py, see the README there."
    )


@pytest.mark.parametrize("benchmark", P.BENCHMARKS, ids=lambda b: b.name)
def test_golden_header_records_its_provenance(benchmark: P.DiodeBenchmark) -> None:
    """A golden file says what made it and under which models.

    Data without provenance is worse than no data, because it looks like
    evidence.
    """
    curve = P.read_golden(str(golden_path(benchmark)))
    assert curve.header["device"] == benchmark.name
    assert curve.header["generator"].startswith("devsim ")
    assert "generated on" in curve.header
    assert "mesh convergence" in curve.header
    assert curve.header["statistics"] == "Boltzmann"
    assert curve.header["recombination"].startswith("SRH only")


@pytest.mark.parametrize("benchmark", P.BENCHMARKS, ids=lambda b: b.name)
def test_golden_header_matches_the_benchmark(benchmark: P.DiodeBenchmark) -> None:
    """The stored curve is the device that parameters.py now describes.

    Editing a doping or a bias list without regenerating leaves a file that
    still loads and still compares, against the wrong device. This is the guard
    against that, and it is why the geometry is written into the header at all.
    """
    curve = P.read_golden(str(golden_path(benchmark)))
    for key, expected in (
        ("Na", benchmark.Na),
        ("Nd", benchmark.Nd),
        ("length", benchmark.length),
        ("junction", benchmark.junction),
        ("tolerance", benchmark.tolerance),
    ):
        assert float(curve.header[key]) == pytest.approx(expected, rel=1e-6), (
            f"{key} in {benchmark.name}.csv is {curve.header[key]} but "
            f"parameters.py now says {expected}. The golden data is stale."
        )

    assert curve.voltage == pytest.approx(list(benchmark.voltages)), (
        "the golden bias points are not the ones parameters.py asks for"
    )


# ------------------------------------------------------------ the comparison

_SOLVED: dict[str, IVCurve] = {}
"""One ddsim sweep per benchmark, reused across the tests that need it."""


def ddsim_curve(benchmark: P.DiodeBenchmark) -> IVCurve:
    """Solve the benchmark in ddsim, once per session."""
    if benchmark.name not in _SOLVED:
        device = pn_diode(
            Na=benchmark.Na,
            Nd=benchmark.Nd,
            length=benchmark.length,
            junction=benchmark.junction,
            n_nodes=benchmark.n_nodes,
            h_min=benchmark.h_min,
        )
        _SOLVED[benchmark.name] = iv_sweep(
            device, "anode", list(benchmark.voltages), step=0.05
        )
    return _SOLVED[benchmark.name]


@pytest.mark.parametrize("benchmark", P.BENCHMARKS, ids=lambda b: b.name)
def test_ddsim_reaches_every_golden_bias(benchmark: P.DiodeBenchmark) -> None:
    """The sweep converges everywhere DEVSIM did.

    Separate from the numerical comparison on purpose. A sweep that stalls at
    0.55 V and a sweep that disagrees by ten percent are different failures and
    should not arrive as the same red line.
    """
    curve = ddsim_curve(benchmark)
    assert curve.complete, f"ddsim stopped early: {curve.message}"
    assert list(curve.voltage) == pytest.approx(list(benchmark.voltages))


@pytest.mark.parametrize("benchmark", P.BENCHMARKS, ids=lambda b: b.name)
def test_ddsim_matches_devsim(benchmark: P.DiodeBenchmark) -> None:
    """The terminal current agrees with DEVSIM at every bias.

    Every point is checked before anything is reported, because the shape of a
    disagreement is the diagnosis. A constant offset across the whole forward
    curve is a mobility or a lifetime that did not match. A disagreement that
    only appears above 0.6 V is high injection. One that only appears in
    reverse bias is generation, or arithmetic.
    """
    golden = P.read_golden(str(golden_path(benchmark)))
    curve = ddsim_curve(benchmark)
    measured = dict(zip(curve.voltage, curve.current, strict=True))

    failures: list[str] = []
    worst = 0.0
    for index, voltage in enumerate(golden.voltage):
        expected = golden.current[index]
        actual = measured[voltage]

        if abs(expected) < P.CURRENT_FLOOR:
            # Zero bias. Both codes are reporting rounding, so the only
            # meaningful question is whether ddsim is also negligible.
            if abs(actual) >= P.CURRENT_FLOOR:
                failures.append(
                    f"{voltage:+.3f} V: devsim gives {expected:.3e} A/cm^2, "
                    f"which is below the {P.CURRENT_FLOOR:.0e} floor, but "
                    f"ddsim gives {actual:.3e}"
                )
            continue

        allowed = max(benchmark.tolerance, NOISE_FACTOR * golden.imbalance(index))
        relative = abs(actual - expected) / abs(expected)
        worst = max(worst, relative / allowed)
        if relative > allowed:
            failures.append(
                f"{voltage:+.3f} V: devsim {expected:.6e}, ddsim {actual:.6e}, "
                f"off by {relative:.2%}, allowed {allowed:.2%}"
            )

    assert not failures, (
        f"{benchmark.name} disagrees with DEVSIM at {len(failures)} of "
        f"{len(golden.voltage)} points:\n  " + "\n  ".join(failures)
    )
    assert worst <= 1.0
